version: "3"

services:
  app:
    labels:
      - dev.orbstack.domains=myapp.local
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      - bundle_cache:/bundle

    ports:
      - "3000:3000"

    command: sleep infinity

    environment:
      REDIS_URL: redis://redis:6379/1
      DB_HOST: db

    depends_on:
      - db
      - redis

  redis:
    labels:
      - dev.orbstack.domains=cache.myapp.local
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    labels:
      - dev.orbstack.domains=db.myapp.local
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mail:
    labels:
      - dev.orbstack.domains=mail.myapp.local
      - dev.orbstack.http-port=8025
    image: marlonb/mailcrab:latest
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres-data:
  bundle_cache:
